name: magento deployment
on:
  workflow_dispatch:
    inputs:
      name:
        description: "target environment name"
        required: true
jobs:
  dev:
    name: dev deployment
    if: ${{ github.event.inputs.name == 'dev'}}
    runs-on: ubuntu-latest
    steps:
    - name: checks
      run: echo "dev"
      
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         password: ${{ secrets.PASSWORD }}
#         port: 22
#         script: echo 'this is dev environment'
  test:
    name: test deployment
    if: ${{ github.event.inputs.name == 'test'}}
    runs-on: ubuntu-latest
    steps:
    - name: checks
      run: echo "test"
    
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         password: ${{ secrets.PASSWORD }}
#         port: 22
#         script: echo 'this is test environment'
  prod:
    name: prod deployment
    if: ${{ github.event.inputs.name == 'prod'}}
    runs-on: ubuntu-latest
    steps:
    - name: checks
      run: echo "prod"
    
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.USERNAME }}
#         password: ${{ secrets.PASSWORD }}
#         port: 22
#         script: echo 'this is test environment'
