name: magento deployment
on:
  workflow_dispatch:
    inputs:
      name:
        description: "target environment name"
        required: true
jobs:
  dev:
    name: dev deployment
    if: ${{ github.event.inputs.name == 'dev'}}
    runs-on: ubuntu-latest
    steps:
    - name: checks
      run: echo "dev"
      
  test:
    name: test deployment
    if: ${{ github.event.inputs.name == 'test'}}
    runs-on: ubuntu-latest
    steps:
    - name: checks
      run: echo "test"
    
  prod:
    name: prod deployment
    if: ${{ github.event.inputs.name == 'prod'}}
    runs-on: ubuntu-latest
    steps:
    - name: checks
      run: echo "prod"

